### ISSUE TITLE
Search with no results should not submit

### ISSUE THREAD

**Issue by rcaught** [ausaccessfed/discovery-service#110]
If no organisations are found in search, pressing "Continue to organisation" or hitting enter should not submit.

<img width="692" alt="Screen Shot 2019-05-07 at 6 22 47 pm" src="https://user-images.githubusercontent.com/144163/57284823-46490600-70f5-11e9-821a-fea9bb41a10d.png">

Presently, it will incorrectly flow to the first IdP in the list.

**Comment by bradleybeddoes** [comment]
Have confimed submit behaviour exists in Chrome and Safari. Firefox behaves as expected (i.e. no submit on blank list).
